# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bae84592cb40c76fe2466c45c07e8a5b740f5cdc34345784df483c2d34a276396197a9aae80ed1789fd49ed384365c4b954e67c21b1c27d344d6c5018cc5b80

test:
  secret_key_base: 4249b199b635be6e8a330de1144300454e434d2a16bf151289b41cdbf9674302b61832940ff378dd6a48968a6efc95e727c683c6855c31918b1db58ea759587b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
